### PR TITLE
Convert HTML XML content (hover, completion) to Markdown XML content

### LINKED ISSUE #109: Hover's & Completions that include XML are broken.
When hovering over `<compilerArgs>` in the following pom.xml:
```XML
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<groupId>demo</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
  
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
				<configuration>
					<compilerArgs>
						<arg>-verbose</arg>
						<arg>-Xlint:all,-options,-path</arg>
					</compilerArgs>
					<annotationProcessorPaths>
						<annotationProcessorPath>
							<groupId>org.hibernate</groupId>
							<artifactId>hibernate-jpamodelgen</artifactId>
							<version>5.2.6.Final</version>
						</annotationProcessorPath>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
```

I get this hover:
```
required: false

Type: List<String>

Expression:

Default Value:

Sets the arguments to be passed to the compiler if {@link #fork} is set to true.Example:

<compilerArgs>  <arg>-Xmaxerrs</arg>  <arg>1000</arg>  <arg>-Xlint</arg>  <arg>-J-Duser.language=en_us</arg></compilerArgs>
```

The formatting of the XML in the `Example:...` is pretty broken and difficult to read due to the loss of newlines.

This issue is also present for completions.

### PR DESCRIPTION
**Pull request by AObuchow**
Fix #109

Signed-off-by: Andrew Obuchowicz <aobuchow@redhat.com>

### CODE REVIEW

File: lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenPluginUtils.java [hunk 1]
```diff
@@ -76,6 +80,20 @@ public static MarkupContent getMarkupDescription(MojoParameter parameter, MojoPa
 		return new MarkupContent("markdown", markdownDescription);
 	}
 
+	private static String htmlXMLToMarkdown(String description) {
+		if (description.contains("<pre>")) {
+			//Add markdown formatting to XML
+			String xmlContent = description.substring(description.indexOf("<pre>") + 6, description.indexOf("</pre>") - 1);
```
Comment (AObuchow) [inline lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenPluginUtils.java:86]: This is pretty hacky currently, but I just wanted get something working first.

**Comment by AObuchow** [comment]
The patch currently gives results like:
image

**Comment by AObuchow** [comment]
@mickaelistria two notes:
- It's a bit ugly how the "Example:" does not start at a new line. I could fix this although it might be a bit hacky.
- Spaces are being used instead of tabs it seems for the XML content. I could change the spaces to tabs.

**Comment by AObuchow** [comment]
@mickaelistria another observation: {@link #fork} is used

File: lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/LocalPluginTest.java [hunk 2]
```diff
@@ -119,6 +119,8 @@ public void testPluginNestedConfigurationHover() throws IOException, Interrupted
 		assertTrue(hoverContents.contains("**Type:** String"));
 		assertTrue(hoverContents.contains("Sets the arguments to be passed to the compiler"));
 		
+		System.out.println(hoverContents);
```
Comment (AObuchow) [inline lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/LocalPluginTest.java:122]: remove
