### PR TITLE
Validate dependency

### LINKED ISSUE #478: Validate dependency
When you declare bad dependency, you have no error

For instance if you have those dependencies, you have no error:

```
<dependency>
	<groupId>BAD_GROUP_ID</groupId>
	<artifactId>maven-resolver-util</artifactId>
	<version>${maven-resolver.version}</version>
	<scope>compile</scope>
</dependency>
```

```xml
<dependency>
	<groupId>org.apache.maven.resolver</groupId>
	<artifactId>BAD_ARTIFACT_ID</artifactId>
	<version>${maven-resolver.version}</version>
	<scope>compile</scope>
</dependency>
```

```xml
<dependency>
	<groupId>org.apache.maven.resolver</groupId>
	<artifactId>maven-resolver-util</artifactId>
	<version>BAD_VERSION</version>
	<scope>compile</scope>
</dependency>
```

### PR DESCRIPTION
**Pull request by angelozerr**
Validate dependency

Fixes #478

Here a basic validation when artifact is not valid. This PR could be improved because today it higlight the full artifact element. It should be nice to improve it to highlight the error for groupid, artifactid, version etc, but I think it is a good start for dependency validation.

Here a demo:

DependencyValidator

### CODE REVIEW

File: lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/participants/diagnostics/MavenDiagnosticParticipant.java [hunk 1]
```diff
@@ -133,8 +139,8 @@ private Diagnostic toDiagnostic(@Nonnull ModelProblem problem) {
 	private DiagnosticSeverity toDiagnosticSeverity(Severity severity) {
 		return switch (severity) {
 			case ERROR, FATAL -> DiagnosticSeverity.Error;
-			case WARNING -> DiagnosticSeverity.Warning;
-			default -> DiagnosticSeverity.Information;
+		case WARNING -> DiagnosticSeverity.Warning;
```
Comment (vrubezhny) [inline lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/participants/diagnostics/MavenDiagnosticParticipant.java:142]: The indentation is broken in this and the following line.

File: lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/LoadedMavenProject.java [hunk 2]
```diff
@@ -0,0 +1,39 @@
+package org.eclipse.lemminx.extensions.maven;
```
Comment (vrubezhny) [inline lemminx-maven/src/main/java/org/eclipse/lemminx/extensions/maven/LoadedMavenProject.java:1]: Please add comment header and some JavaDoc-comments.

**Review by vrubezhny — COMMENTED** [review]
Looks good!

Please add comment headers for the new class .

**Review by vrubezhny — APPROVED** [review]
The PR looks good. Thanks!
