### PR TITLE
Test hover when multiple properties are in a tag

### LINKED ISSUE #117: Hover with multiple properties in the same tag doesn't work
Hovering on "${bar}" in the following pom gives a hover for "foo":
```XML
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.test</groupId>
	<artifactId>test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>pom</packaging>

	<properties>
		<foo>$</foo>
		<bar>test</bar>
	</properties>
	<contributors>
		<contributor>
			<name>${foo}   ${bar}</name>
		</contributor>
	</contributors>
</project>
```

image

### PR DESCRIPTION
**Pull request by AObuchow**
Fix #117

Signed-off-by: Andrew Obuchowicz <aobuchow@redhat.com>

### CODE REVIEW

File: lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/SimpleModelTest.java [hunk 1]
```diff
@@ -191,6 +191,29 @@ public void testPropertyDefinitionSameDocument() throws IOException, Interrupted
...
+ 	public void testMultiplePropertyHover() throws IOException, InterruptedException, ExecutionException, URISyntaxException {
+		DOMDocument document = createDOMDocument("/pom-with-multiple-properties.xml", languageService);
+		Position pos = new Position(16, 12);
+		Hover hover = languageService.doHover(document,pos, new SharedSettings());
+		System.out.println((((MarkupContent) hover.getContents().getRight()).getValue()));
+		System.out.println(hover.getRange());
+		Range firstHoverRange = hover.getRange();
+		
+
+		//DOMNode propertyNode = DOMUtils.findNodesByLocalName(document, "myProperty").stream().filter(node -> node.getParentElement().getLocalName().equals("properties")).collect(Collectors.toList()).get(0);;
```
Comment (AObuchow) [inline lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/SimpleModelTest.java:204]: Remove

File: lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java [hunk 2]
```diff
@@ -335,8 +339,20 @@ private Hover collectProperty(IPositionRequest request, String property) {
 			for (Entry<String, String> prop : allProps.entrySet()) {
 				String mavenProperty = prop.getKey();
 				if (property.equals(mavenProperty)) {
-					return new Hover(new MarkupContent("markdown", "Property: " + mavenProperty
+					Hover hover = new Hover(new MarkupContent("markdown", "Property: " + mavenProperty
 							+ MavenPluginUtils.LINE_BREAK + "Value: " + prop.getValue() + MavenPluginUtils.LINE_BREAK));
+					try {
+						Position propertyStart = new Position(request.getPosition().getLine(),
```
Comment (AObuchow) [inline lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java:345]: This is code copied from MavenDefinitionParticipant. It should be factored into a function

**Comment by AObuchow** [comment]
@mickaelistria this commit now adds a range but the same bug still occurs when testing as a user. I'm going to investigate further.

File: lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java [hunk 3]
```diff
@@ -146,16 +152,18 @@ private Hover collectArtifactDescription(IHoverRequest request, boolean isPlugin
...
-				.map(file -> builder.buildRawModel(file, ModelBuildingRequest.VALIDATION_LEVEL_MINIMAL, false).get())
-				.map(model -> model.getName() + "\n\n" + model.getDescription())
-				.map(message -> (message.length() > 2 ? message : null));
+					.filter(gav -> (artifactToSearch.getGroupId() == null
+							|| artifactToSearch.getGroupId().equals(gav.getGroupId()))
+							&& (artifactToSearch.getArtifactId() == null
+									|| artifactToSearch.getArtifactId().equals(gav.getArtifactId()))
+							&& (artifactToSearch.getVersion() == null
+									|| artifactToSearch.getVersion().equals(gav.getVersion())))
+					.sorted(Comparator.comparing((Gav gav) -> new DefaultArtifactVersion(gav.getVersion())).reversed())
```
Comment (AObuchow) [inline lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java:161]: Didn't intend to format all this..

**Comment by AObuchow** [comment]
My current assumption is that an upstream fix is required for onText hover, but I have to check first

File: lemminx-maven/src/main/java/org/eclipse/lemminx/maven/DOMUtils.java [hunk 4]
```diff
@@ -61,6 +64,29 @@ public static DOMNode findClosestParentNode(final IPositionRequest request, fina
...
+	 * node
+	 * 
+	 * @param request
+	 * @param text
+	 * @return the range of the specificed text within the IPositionRequest's node,
+	 *         or null if the text could not be found in the node.
+	 * @throws DOMException
+	 * @throws BadLocationException
+	 */
+	public static Range getTextRange(IPositionRequest request, String text) throws DOMException, BadLocationException {
```
Comment (mickaelistria) [inline lemminx-maven/src/main/java/org/eclipse/lemminx/maven/DOMUtils.java:79]: I believe this would fail in some case, for example if I use `<blah>${property} ${property}</blah>`, then a request on the 2nd property would result on the range of the 1st one (if I' not mistaken).
Maybe `getMavenPropertyInRequest` should instead return a `Pair<Range, String>` where the range would be the actual range under the request that match a property.

**Comment by AObuchow** [comment]
I think the issue is that LemMinX is using [`mergeHover`](https://github.com/eclipse/lemminx/blob/374ea32776f24a910f6a2541d0f66dd21cff1266/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/services/XMLHover.java#L248).

File: lemminx-maven/src/main/java/org/eclipse/lemminx/maven/DOMUtils.java (hunk 4 above)
Comment (AObuchow) [reply lemminx-maven/src/main/java/org/eclipse/lemminx/maven/DOMUtils.java:79]: @mickaelistria I see the issue your mentioning and agree it should be fixed for this case. However I'm not sure I understand your proposed solution unfortunately. Could you give a more detailed explanation or example?

**Comment by mickaelistria** [comment]
If I'm not mistaken, mergeHover only affects ranges when they're not pre-set. If LemMinX-Maven sets (more correct) ranges explicitly first, then mergeHover doesn't change them.

**Comment by AObuchow** [comment]
> If I'm not mistaken, mergeHover only affects ranges when they're not pre-set. If LemMinX-Maven sets (more correct) ranges explicitly first, then mergeHover doesn't change them.

```Java
		// Find the best hover range
		Range range = defaultRange;
		for (Hover hover : hovers) {
			if (hover.getRange() != null) {
				if (range == null) {
					range = hover.getRange();
				} else {
					// TODO : compute the best range
				}
			}
		}
		return MarkupContentFactory.createHover(contents, range);
```
If multiple hovers are present, it seems to use the range from the first hover in the list of hovers.

File: lemminx-maven/src/main/java/org/eclipse/lemminx/maven/DOMUtils.java (hunk 4 above)
Comment (mickaelistria) [reply lemminx-maven/src/main/java/org/eclipse/lemminx/maven/DOMUtils.java:79]: The operation that finds a property name for a given position is actually iterating on the string and this same iteration can be used to find the range. As it appears the range is important, and that just looking for a substring is too weak, then we should also return the range when returning the property name.

**Comment by AObuchow** [comment]
Upon debugging, mergeHovers only receives 1 hover so that's not causing the issue.

**Comment by mickaelistria** [comment]
@AObuchow is there any progress here?

**Comment by AObuchow** [comment]
> @AObuchow is there any progress here?

Yes sorry for the delay, I will be submitting a new PR today.
I've implemented the changes requested and while doing so I think I realized where the bug was originating.
`collectProperty` in MavenHoverParticipant was calling `DOMUtils.getTextRange()` which only finds the first occurrence range of a string in a node. It should instead be returning a list of occurrence ranges.

**Comment by mickaelistria** [comment]
I think such `DOMUtils.getTextRange()` should simply doesn't exist at all, and a similar method should instead take as parameter the position, to prefer the instance of the string which is under given position.

**Comment by AObuchow** [comment]
> I think such `DOMUtils.getTextRange()` should simply doesn't exist at all, and a similar method should instead take as parameter the position, to prefer the instance of the string which is under given position.

Agreed, I'll do this

**Comment by AObuchow** [comment]
Confusingly, https://github.com/eclipse/lemminx-maven/issues/107 seems to be occurring again (I'm going to add a dedicated test which I should have already added), and the issue this PR addresses is not fixed.

File: lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/SimpleModelTest.java [hunk 5]
```diff
@@ -191,6 +191,55 @@ public void testPropertyDefinitionSameDocument() throws IOException, Interrupted
...
+  		assertTrue((((MarkupContent) hover.getContents().getRight()).getValue().contains("test")));
+  		assertFalse(firstHoverRange.equals(secondHoverRange));
+	}
+	
+	@Test
+ 	public void testMultiplePropertyDefinitionRangeSameTag() throws IOException, InterruptedException, ExecutionException, URISyntaxException {
+		DOMDocument document = createDOMDocument("/pom-with-multiple-properties.xml", languageService);
+		Position pos = new Position(16, 12);
+		
+		List<? extends LocationLink> definitionLinks = languageService.findDefinition(document, pos, () -> {
```
Comment (AObuchow) [inline lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/SimpleModelTest.java:214]: Format this, remove println's

File: lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java [hunk 6]
```diff
@@ -339,15 +344,26 @@ public static String getMavenPropertyInRequest(IPositionRequest request) {
...
 		if (indexOpen > indexCloseBefore) {
-			return tagText.substring(indexOpen + 2, indexCloseAfter + beforeHover);
+			Position propertyStart;
+			try {
+				String propertyText = tagText.substring(indexOpen + 2, indexCloseAfter + beforeHover);
+				propertyStart = new Position(request.getPosition().getLine(),
+						request.getXMLDocument().positionAt(request.getNode().getStart()).getCharacter() + indexOpen);
+				
+				// 3 is added to the end position's character to compensate for the '${}' 
+				Range propertyRange = new Range(propertyStart, new Position(request.getPosition().getLine(),
```
Comment (AObuchow) [inline lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java:354]: This works although it could probably be a bit more elegant, but shouldn't be a blocker

File: lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java [hunk 7]
```diff
@@ -339,15 +344,26 @@ public static String getMavenPropertyInRequest(IPositionRequest request) {
 		int indexCloseBefore = beforeHoverText.lastIndexOf('}');
 		int indexCloseAfter = afterHoverText.indexOf('}');
 		if (indexOpen > indexCloseBefore) {
-			return tagText.substring(indexOpen + 2, indexCloseAfter + beforeHover);
+			Position propertyStart;
+			try {
+				String propertyText = tagText.substring(indexOpen + 2, indexCloseAfter + beforeHover);
+				propertyStart = new Position(request.getPosition().getLine(),
```
Comment (mickaelistria) [inline lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java:350]: What about just `positionStart = request.getXMLDocument().positionAt(request.getNode().getStart() + indexOpen)` ?

File: lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java (hunk 6 above)
Comment (mickaelistria) [reply lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenHoverParticipant.java:354]: similarly
```java
int textStart = request.getNode().getStart();
Range propertyRange = XMLPositionUtility.createRange(textStart + indexOpen + 2, textStart + indexCloseAfter - 1, request.getXMLDocument());
```

**Comment by AObuchow** [comment]
@mickaelistria this should be good to merge now
