### PR TITLE
Fix jumping to wrong tag on property definition

### LINKED ISSUE #83: Jump to property definition can be erroneous when other tags have property name
From lemminx-maven's own pom.xml

```

	<properties>
		<lemminx.maven.indexDirectory>${project.build.directory}/test-index</lemminx.maven.indexDirectory>
		<maven.repo.local>${settings.localRepository}</maven.repo.local>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.2</version> <!-- Need to be same as in tests so we're sure version in in local repo -->
				<configuration>
					<test>org.eclipse.lemminx.maven.test.AllTests</test>
					<systemPropertyVariables>
						<lemminx.maven.indexDirectory>${lemminx.maven.indexDirectory}</lemminx.maven.indexDirectory>
						<maven.repo.local>${maven.repo.local}</maven.repo.local>
					</systemPropertyVariables>
				</configuration>
			</plugin>
		</plugins>
	</build>

```

Ctrl+click on `${lemminx.maven.indexDirectory}` selects the parent node instead of selecting the property definition under `<properties>`.

### PR DESCRIPTION
**Pull request by AObuchow**
Fix #83

Signed-off-by: Andrew Obuchowicz <aobuchow@redhat.com>

### CODE REVIEW

File: lemminx-maven/src/main/java/org/eclipse/lemminx/maven/DOMUtils.java [hunk 1]
```diff
@@ -40,24 +42,25 @@ public static DOMNode findClosestParentNode(final IPositionRequest request, fina
 		return null;
 	}
 	
-	// TODO: use optional?
-	public static DOMNode findNodeByLocalName(final DOMDocument document, final String localName) {
+	// TODO: should be returning a List<DOMNode> as there can be duplicates
```
Comment (AObuchow) [inline lemminx-maven/src/main/java/org/eclipse/lemminx/maven/DOMUtils.java:45]: Remove this TODO

File: lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/SimpleModelTest.java [hunk 2]
```diff
@@ -155,7 +156,25 @@ public void testPropertyDefinitionSameDocument() throws IOException, Interrupted
...
+		DOMNode propertyNode = DOMUtils.findNodesByLocalName(targetDocument, "myProperty").stream().filter(node -> node.getParentElement().getLocalName().equals("properties")).collect(Collectors.toList()).get(0);;
+		Range expectedTargetRange = XMLPositionUtility.createRange(propertyNode);
+		assertTrue(definitionLinks.stream().anyMatch(link -> link.getTargetUri().equals(targetDocument.getDocumentURI())));
+		assertTrue(definitionLinks.stream().anyMatch(link -> link.getTargetRange().equals(expectedTargetRange)));
+		assertTrue(definitionLinks.stream().anyMatch(link -> link.getTargetSelectionRange().equals(expectedTargetRange)));
+	}
+	
+	// TODO: Name this better
+	@Test
+ 	public void testPropertyDefinitionSameDocumentBug() throws IOException, InterruptedException, ExecutionException, URISyntaxException {
```
Comment (AObuchow) [inline lemminx-maven/src/test/java/org/eclipse/lemminx/maven/test/SimpleModelTest.java:168]: Should be given a better name probably.

**Comment by mickaelistria** [comment]
This looks good to me.
